export const HERO_VERBS = [
  'think about',
  'contemplate',
  'ponder',
  'wonder about',
  'muse on',
  'ruminate on',
  'dream about',
  'daydream about',
  'obsess over',
  'theorize about',
  'philosophize about',
  'speculate about',
  'chew on',
  'mull over',
  'puzzle over',
  'geek out about',
  'nerd out over',
  'noodle on',
  'marinate on',
  'mull about',
  'brood over',
  'fixate on',
  'fantasize about',
  'hypothesize about',
  'unpack',
  'dissect',
  'interrogate',
  'excavate',
  'untangle',
  'overthink',
  'overanalyze',
  'spiral about',
  'rabbit-hole on',
  'deep-dive into',
  'doomscroll about',
  'lie awake pondering',
  'lose sleep over',
  'stay up thinking about',
  'churn on',
  'percolate on',
  'incubate ideas about',
  'gestate thoughts on',
  'freewheel about',
  'riff on',
  'wax poetic about',
  'wax philosophical about',
  'lose myself in thoughts of',
  'get lost thinking about',
  'spiral into thoughts of',
  'read up on',
  'dig into',
  'burrow into',
  'tinker with theories of',
  'sketch out theories on',
  'whiteboard',
  'daydream in circles about',
  'circle back to thoughts of',
  'chase rabbit holes about',
  'go down rabbit holes on',
  'keep coming back to',
  'quietly panic about',
  'low-key panic about',
  'nerd-snipe myself with',
] as const;
